---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/15 14:18
---
local _M = {}
local mt = {__index = _M}

function _M.deposit(self, v)
    self.balance = self.balance + v
end
function _M.withdraw(self, v)
    if self.balance > v then
        self.balance = self.balance - v
    else
        error("insufficient funds")
    end
end
function _M.new(self, balance)
    balance = balance or 0
    -- 自己的表中找不到deposit、withdraw这些方法和变量时，便会到__index所指定的_M类型中去寻找
    return setmetatable({balance = balance}, mt)
end
return _M
