---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/15 14:27
---
local account = require("oop.account")

local a = account:new()
a:deposit(100)

local b = account:new()
b:deposit(50)

print(a.balance)
print(b.balance)
