---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/15 11:30
---
functor = {[1] = "hello"}
-- 仿函数，表的行为表现得像一个函数，接受参数，实现调用
function func1(self, arg)
    print("called from", arg)
end
setmetatable(functor, {__call = func1})
functor("functo")
