---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/15 11:45
---
-- 保护对象，使其无法看到和修改metatable
object = setmetatable({}, {__metatable = "you can not access here"})
print(getmetatable(object))
setmetatable(object, {})