---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/15 11:11
---
arr = {2, 3, 4}
-- 类似于在JAVA中重写toString方法
arr = setmetatable(arr, {__tostring = function(self)
    local result = "{"
    local sep = ""
    for _, j in pairs(self) do
        result = result.. sep.. j
        sep = ", "
    end
    result = result .. "}"
    return result
end})
print(arr)