---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/13 19:28
---
local set1 = {10, 20, 30}
local set2 = {20, 40, 50}
local union = function (self, another)
    local set = {}
    local result = {}
    for i, j in pairs(self) do
        set[j] = true
    end
    for i, j in pairs(another) do
        set[j] = true
    end
    for i, j in pairs(set) do table.insert(result, i)
    end
    return result
end
setmetatable(set1, {__add = union})
local set3 = set1 + set2
for _, j in pairs(set3) do
    io.write(j.." ")
end
