---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/19 11:10
---

-- 判断一个table是否为{}，不能采用#table == 0 的方式来判断。使用next指令
local next = next
local a = {}
local b = {name = "Bob", sex = "Male"}
local c = {"Male", "Female"}
local d = nil

print(#a)
print(#b)
print(#c)
--print(#d) 报错

if a == nil then
    print("a == nil")
end

if b == nil then
    print("b == nil")
end

if c == nil then
    print("c == nil")
end

if d == nil then
    print("d == nil")
end

if next(a) == nil then
    print("next(a) == nil")
end

if next(b) == nil then
    print("next(b) == nil")
end

if next(c) == nil then
    print("next(c) == nil")
end
