---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/19 10:46
---

-- #操作符和table.getn(table)计算数组（表中除去键值对的长度）的长度，以nil为结尾
local tblTest1 = {1, a = 2, 3}
print("test1 "..#(tblTest1).." "..table.getn(tblTest1))

local tblTest2 = {1, nil}
print("test2 "..#(tblTest2).." "..table.getn(tblTest2))

local tblTest3 = {1, nil, 2}
print("test3 "..#(tblTest3).." "..table.getn(tblTest3))

local tblTest4 = {1, nil, 2, nil}
print("test4 "..#(tblTest4).." "..table.getn(tblTest4))

local tblTest5 = {1, nil, 2, nil, 3, nil}
print("test5 "..#(tblTest5).." "..table.getn(tblTest5))

local tblTest6 = {1, nil, 2, nil, 3, nil}
print("test6 "..#(tblTest6).." "..table.getn(tblTest6))
