---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/19 11:41
---
local s = "hello, world"
local i,j = string.find(s, "hello")
print(i, j)

local s = "hello world from Lua"
for w in string.gmatch(s, "%a+") do
    print(w)
end

local a = "Lua is cute"
local b = string.gsub(a, "cute", "great")
print(a)
print(b)

print(string.gsub("ab (enclosed (in) parentheses) (helo)linefas", "%b()", ""))
