---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/19 10:18
---
local _M = {_VERSION = '0.01'}

function _M.add(a, b)
    return a + b
end

function _M.update_A()
    A = 365
end

return _M