---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/19 10:05
---
-- x为全局变量，i为局部变量
x = 10
local i = 1

while i<=x do
    -- 局部变量
    local x = i * 2
    print(x)
    i = i + 1
end

if i > 20 then
    -- 局部变量
    local x
    x = 20
    print(x + 2)
else
    -- 全局变量
    print(x)
end

-- 全局变量
print(x)
