---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/19 10:20
---
A = 360
local foo = require("local.foo")

local b = foo.add(A, A)
print("b=", b)

foo.update_A()
print("A=", A)