---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/15 15:12
---
local _M = {}

local mt = {__index = _M}

function _M.upper(s)
    return string.upper(s)
end

return _M