---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/15 15:14
---
local s_base = require("oop.inherit.s_base")

local _M = {}
_M = setmetatable(_M, {__index = s_base})

function _M.lower(s)
    return string.lower(s)
end

return _M