---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/15 15:16
---
local s_more = require("oop.inherit.s_more")

print(s_more.upper("Hello"))
print(s_more.lower("Hello"))