---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jj.
--- DateTime: 2020/1/27 0:14
---
-- 冒号操作符会自动带入一个self参数，类似于JAVA中的实例方法。
-- 逗号需要显式传入
local str = "abcde"
print("case 1:", str:sub(1,2))
print("case 2:", str.sub(str, 1, 2))
